# Generated by Django 2.1.3 on 2019-01-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisonMatchApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='media')),
            ],
        ),
    ]
