# Generated by Django 2.0.2 on 2019-01-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisonMatchApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='user_profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Lustudent',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=256)),
                ('lnumber', models.CharField(db_column='LNumber', max_length=255, primary_key=True, serialize=False)),
                ('emailaddress', models.CharField(db_column='EmailAddress', max_length=256)),
                ('major', models.CharField(db_column='Major', max_length=50)),
                ('bio', models.CharField(db_column='Bio', max_length=256)),
                ('idealdate', models.CharField(db_column='IdealDate', max_length=256)),
                ('gender', models.IntegerField(db_column='Gender')),
                ('ans1', models.IntegerField(db_column='Ans1')),
                ('ans2', models.IntegerField(db_column='Ans2')),
                ('ans3', models.IntegerField(db_column='Ans3')),
                ('ans4', models.IntegerField(db_column='Ans4')),
                ('ans5', models.IntegerField(db_column='Ans5')),
                ('ans6', models.IntegerField(db_column='Ans6')),
                ('ans7', models.IntegerField(db_column='Ans7')),
                ('ans8', models.IntegerField(db_column='Ans8')),
                ('ans9', models.IntegerField(db_column='Ans9')),
                ('ans10', models.IntegerField(db_column='Ans10')),
                ('profilepicurl', models.CharField(db_column='ProfilePicUrl', max_length=2083)),
                ('paid', models.IntegerField(db_column='Paid')),
            ],
            options={
                'db_table': 'LUStudent',
                'managed': True,
            },
        ),
    ]
